// Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of element from the array.
// Note: AND is bitwise '&' operator.


// Example 1:

// Input: 
// N = 4
// arr[] = {4, 8, 12, 16}
// Output: 8
// Explanation:
// Pair (8,12) has the Maximum AND Value 8.

// O(n^2)

// public class maxAndValue {
//     public static void main(String[] args) {
//         int n=4;

//         int arr[]={4,8,16,2};

//         int max=arr[0] & arr[1];

//         for(int i=0;i<arr.length;i++){
//             for(int j=i+1;j<arr.length;j++){
//                 if((arr[i] & arr[j]) >max)
//                 max=arr[i] & arr[j];
//             }
//         }

//         System.out.println(max);
//     }
// }

// o(nlog(m))


public class maxAndValue {
    public static void main(String[] args) {

        int arr[]={4,8,12,16};

        int res=0,count;

        for(int i=31;i>=0;i--){
            count=checkBit(res | (1<<i),arr);

            if(count>=2)
            res|=(1<<i);
        }

        System.out.println(res);
    }

    static int checkBit(int pattern,int arr[]){
        int count=0;
        for(int i=0;i<arr.length;i++){
            if((arr[i]&pattern)==pattern)
            count++;
        }

        return count;
    }
}